stages:
  - test
image: python:3.6
services:
  - mysql
variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: "testdb_apis"
  MYSQL_ROOT_PASSWORD: "sggdjagg"
  GIT_STRATEGY: clone
test:
  tags:
          - python
  stage: test
  script:
          - export DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@127.0.0.1:3306/$MYSQL_DATABASE
          - python -m pip install -r requirements.txt
          - python -m pip install mysqlclient
          - python manage.py test --settings=apis.settings.test

