stages:
  - test
image: python:3.6
services:
  - mysql
variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: "testdb_apis"
  MYSQL_ROOT_PASSWORD: "sggdjagg"
test:
  stage: test
  script:
          - export DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@localhost:3306/$MYSQL_DATABASE 
          - python3 -m pip install -r requirements.txt
          - python3 manage.py test --settings=apis.settings.test

