stages:
  - test
image: python:3.6
services:
  - mysql:5.7
variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: "testdb_apis"
  MYSQL_ROOT_PASSWORD: "sggdjagg"
  GIT_STRATEGY: clone
test:
  tags:
          - python
  stage: test
  script:
          - export DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@mysql:3306/$MYSQL_DATABASE
          - python -m pip install -r requirements.txt
          - python -m pip install mysqlclient
          - sed -i '18,19 s/^/#/' apis/urls.py
          - mkdir /build/apis/apis-core
          - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/acdh-oeaw/apis/apis-core.git /build/apis/apis-core
          - ln -s ../apis-core/apis_core apis_core
          - ls /build/apis
          - python manage.py makemigrations --settings=apis.settings.settings_test_ci
          - python manage.py migrate --settings=apis.settings.settings_test_ci
          - sed -i '18,19 s/^#//' apis/urls.py
          - python manage.py makemigrations --settings=apis.settings.settings_test_ci
          - python manage.py migrate --settings=apis.settings.settings_test_ci
          - python manage.py test --settings=apis.settings.settings_test_ci

