stages:
  - test
  - deploy
image: python:3.6

deploy:
  only:
    refs:
      - master
  stage: deploy
  trigger: acdh-oeaw/apis/apis-docker
  variables:
      APIS_TRIGGERD_BY: 'apis-webpage-base'
      APIS_VERSION: '0.9'
