# Generated by Django 2.2.1 on 2019-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='norm_url',
            field=models.URLField(blank=True, help_text='URL to any normdata record of the person', max_length=300, verbose_name='Norm Data URL (OCRID, GND, VIAF, ...)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='website',
            field=models.URLField(blank=True, max_length=300, verbose_name="Link to the person's website"),
        ),
    ]
