# Generated by Django 2.2.1 on 2019-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_auto_20190605_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Short description of the Person')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name="Link to the person's website")),
                ('logo_url', models.URLField(blank=True, max_length=300, verbose_name="Link to the Insitution's Logo")),
                ('norm_url', models.URLField(blank=True, help_text='URL to any normdata record of the institution', max_length=300, verbose_name='Norm Data URL (OCRID, GND, VIAF, ...)')),
            ],
            options={
                'verbose_name': 'Institution involved in the Project',
                'ordering': ['name'],
            },
        ),
    ]
