# Generated by Django 2.2.1 on 2019-06-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_projectinst'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinst',
            name='abbr',
            field=models.CharField(blank=True, max_length=300, verbose_name='Abbreviation'),
        ),
    ]
